const LAYOUT_DEFAULTS={main:['news','red','assets','add','provider'],rail:['utility'],newsSide:['sources','rules','watchlist','forecast']};
function loadLayout(){try{return {...LAYOUT_DEFAULTS,...JSON.parse(localStorage.getItem('td_layout_v8')||'{}')}}catch{return {...LAYOUT_DEFAULTS}}}
function saveLayout(state){localStorage.setItem('td_layout_v8',JSON.stringify(state))}
let LAYOUT_STATE=loadLayout();
let layoutEditMode=false;
function reorderChildren(container,order,selector){const map={};Array.from(container.querySelectorAll(selector)).forEach(el=>map[el.dataset.layoutId||el.dataset.tileId]=el);order.forEach(id=>{if(map[id])container.appendChild(map[id])})}
function applyLayout(){const main=document.querySelector('[data-layout-zone="main"]');if(main)reorderChildren(main,LAYOUT_STATE.main,'.draggable-section');const rail=document.querySelector('[data-layout-zone="rail"]');if(rail)reorderChildren(rail,LAYOUT_STATE.rail,'.draggable-tile');const newsSide=document.querySelector('[data-layout-zone="newsSide"]');if(newsSide)reorderChildren(newsSide,LAYOUT_STATE.newsSide,'.draggable-tile')}
function serializeZone(container,selector,key){LAYOUT_STATE[key]=Array.from(container.querySelectorAll(selector)).map(el=>el.dataset.layoutId||el.dataset.tileId);saveLayout(LAYOUT_STATE)}
function enableDnD(selector,key){document.querySelectorAll(selector).forEach(el=>{el.setAttribute('draggable',layoutEditMode?'true':'false');el.ondragstart=e=>{if(!layoutEditMode)return e.preventDefault();el.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',el.dataset.layoutId||el.dataset.tileId)};el.ondragend=()=>el.classList.remove('dragging')})}
function wireZone(container,selector,key){if(!container)return;container.ondragover=e=>{if(!layoutEditMode)return; e.preventDefault(); const after=getDragAfterElement(container,e.clientY,selector); const dragging=container.querySelector('.dragging'); if(!dragging)return; if(after==null)container.appendChild(dragging); else container.insertBefore(dragging,after)};container.ondrop=e=>{if(!layoutEditMode)return; e.preventDefault(); serializeZone(container,selector,key)}}
function getDragAfterElement(container,y,selector){const els=[...container.querySelectorAll(selector+':not(.dragging)')];return els.reduce((closest,child)=>{const box=child.getBoundingClientRect();const offset=y-box.top-box.height/2;return offset<0&&offset>closest.offset?{offset,element:child}:closest},{offset:Number.NEGATIVE_INFINITY}).element}
function toggleLayoutEdit(){layoutEditMode=!layoutEditMode;document.body.classList.toggle('layout-edit',layoutEditMode);const btn=document.getElementById('toggleLayoutBtn');if(btn)btn.textContent=layoutEditMode?'Lock Layout':'Customize Layout';enableDnD('.draggable-section','main');enableDnD('[data-layout-zone="rail"] .draggable-tile','rail');enableDnD('[data-layout-zone="newsSide"] .draggable-tile','newsSide')}
function resetLayout(){LAYOUT_STATE={...LAYOUT_DEFAULTS};saveLayout(LAYOUT_STATE);applyLayout()}
window.toggleLayoutEdit=toggleLayoutEdit;window.resetLayout=resetLayout;
