const DEFAULT_GLOBALS={finnhubToken:"",weeklyEventsText:`2026-03-18 08:30|USD CPI|USD\n2026-03-19 08:30|US Initial Jobless Claims|USD\n2026-03-19 10:00|US Existing Home Sales|USD\n2026-03-20 08:30|Canada Retail Sales|CAD`,manualResultNotes:""};
const DEFAULT_SETTINGS={refreshSeconds:60,newsSeconds:300,chartInterval:"15",liteDefault:false,theme:"macro-command",tileStyle:"glass",glow:"low",density:"comfortable",innerEdgeTheme:"theme",redFolderTab:"next"};
const ACCENTS={cyan:{hex:'#67e8f9',rgb:'103,232,249'},lime:{hex:'#84cc16',rgb:'132,204,22'},amber:{hex:'#fbbf24',rgb:'251,191,36'},red:{hex:'#f87171',rgb:'248,113,113'},ice:{hex:'#c4f1ff',rgb:'196,241,255'},white:{hex:'#ffffff',rgb:'255,255,255'},purple:{hex:'#c084fc',rgb:'192,132,252'}};
const CRYPTO_CG_MAP={BTCUSD:"bitcoin",ETHUSD:"ethereum",SOLUSD:"solana",XRPUSD:"ripple",ADAUSD:"cardano",DOGEUSD:"dogecoin"};
const FUTURES_PROXY_MAP={ES:{proxySymbol:"SPY",chartSymbol:"AMEX:SPY",quoteSymbol:"SPY",note:"Using SPY as ES proxy."},MES:{proxySymbol:"SPY",chartSymbol:"AMEX:SPY",quoteSymbol:"SPY",note:"Using SPY as MES proxy."},NQ:{proxySymbol:"QQQ",chartSymbol:"NASDAQ:QQQ",quoteSymbol:"QQQ",note:"Using QQQ as NQ proxy."},MNQ:{proxySymbol:"QQQ",chartSymbol:"NASDAQ:QQQ",quoteSymbol:"QQQ",note:"Using QQQ as MNQ proxy."},GC:{proxySymbol:"XAUUSD",chartSymbol:"OANDA:XAUUSD",quoteSymbol:"XAUUSD",note:"Using XAUUSD as GC proxy."},MGC:{proxySymbol:"XAUUSD",chartSymbol:"OANDA:XAUUSD",quoteSymbol:"XAUUSD",note:"Using XAUUSD as MGC proxy."},CL:{proxySymbol:"USOIL",chartSymbol:"OANDA:WTICOUSD",quoteSymbol:"USOIL",note:"Using WTI proxy for CL."},MCL:{proxySymbol:"USOIL",chartSymbol:"OANDA:WTICOUSD",quoteSymbol:"USOIL",note:"Using WTI proxy for MCL."}};
const DEFAULT_ASSETS=[{id:mkid(),symbol:"USDJPY",assetClass:"forex",priceSource:"manual",currentPrice:149.5,previousPrice:149.45,pdh:149.8,pdl:149.1,retestBuffer:0.05,autoPrice:false,lastSource:"Manual",priceStatus:"Manual",updatedAt:null},{id:mkid(),symbol:"BTCUSD",assetClass:"crypto",priceSource:"coingecko",currentPrice:80000,previousPrice:79800,pdh:81200,pdl:78500,retestBuffer:120,autoPrice:true,lastSource:"CoinGecko",priceStatus:"Pending",updatedAt:null}];
const CLOCKS=[{city:"New York",tz:"America/New_York",label:"NYSE / Nasdaq",open:9,close:16},{city:"Chicago",tz:"America/Chicago",label:"CME",open:8,close:16},{city:"London",tz:"Europe/London",label:"LSE",open:8,close:16.5},{city:"Frankfurt",tz:"Europe/Berlin",label:"Xetra",open:9,close:17.5},{city:"Tokyo",tz:"Asia/Tokyo",label:"TSE",open:9,close:15},{city:"Hong Kong",tz:"Asia/Hong_Kong",label:"HKEX",open:9.5,close:16}];
const NEWS_INTEL_SOURCES={lynalden:{name:"Lyn Alden",score:86,forecast:82},hedgeye:{name:"Hedgeye",score:81,forecast:75},fxstreet:{name:"FXStreet",score:78,forecast:72},investinglive:{name:"investingLive",score:77,forecast:71},kobeissi:{name:"Kobeissi",score:69,forecast:66},coinbureau:{name:"Coin Bureau",score:71,forecast:67},realvision:{name:"Real Vision",score:74,forecast:69},zerohedge:{name:"ZeroHedge",score:54,forecast:45},cointelegraph:{name:"Cointelegraph",score:66,forecast:58}};
let GLOBALS=loadObject('td_globals_fixed',DEFAULT_GLOBALS),SETTINGS=loadObject('td_settings_core_v7',DEFAULT_SETTINGS),ASSETS=loadArray('td_assets_fixed',DEFAULT_ASSETS),NEWS_INTEL_STORIES=[],lastPriceRefresh=0,newsHealth='Unknown',priceHealth='Unknown';
function mkid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(16).slice(2)}
const $=id=>document.getElementById(id);
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function formatPrice(v){const n=Number(v);if(!Number.isFinite(n))return'-';if(Math.abs(n)>=1000)return n.toFixed(2);if(Math.abs(n)>=100)return n.toFixed(3);if(Math.abs(n)>=1)return n.toFixed(3);return n.toFixed(5)}
function formatAgo(ms){const mins=Math.max(0,Math.round((Date.now()-ms)/60000));if(mins<60)return `${mins}m ago`;const h=Math.floor(mins/60),m=mins%60;return `${h}h ${m}m ago`}
function formatCountdown(target){const diff=Math.max(0,Math.floor((target-Date.now())/1000));const h=Math.floor(diff/3600),m=Math.floor((diff%3600)/60),s=diff%60;return `${h}h ${m}m ${s}s`}
function loadObject(k,f){try{const r=localStorage.getItem(k);return r?{...f,...JSON.parse(r)}:{...f}}catch{return{...f}}}
function loadArray(k,f){try{const r=localStorage.getItem(k),a=r?JSON.parse(r):null;return Array.isArray(a)&&a.length?a:JSON.parse(JSON.stringify(f))}catch{return JSON.parse(JSON.stringify(f))}}
function saveGlobals(){localStorage.setItem('td_globals_fixed',JSON.stringify(GLOBALS))}
function saveSettings(){localStorage.setItem('td_settings_core_v7',JSON.stringify(SETTINGS))}
function saveAssets(){localStorage.setItem('td_assets_fixed',JSON.stringify(ASSETS))}
function safeParseNum(v){const n=parseFloat(v);return Number.isFinite(n)?n:null}
async function safeTextFetch(url,timeoutMs=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{signal:c.signal,cache:'no-store'});clearTimeout(t);if(!r.ok)return null;return await r.text()}catch{clearTimeout(t);return null}}
async function safeJsonFetch(url,timeoutMs=5000){const txt=await safeTextFetch(url,timeoutMs);if(!txt)return null;try{return JSON.parse(txt)}catch{return null}}
function applyTheme(){document.body.dataset.theme=SETTINGS.theme||'macro-command';document.body.dataset.tile=SETTINGS.tileStyle||'glass';document.body.dataset.glow=SETTINGS.glow||'low';document.body.dataset.density=SETTINGS.density||'comfortable';document.body.classList.toggle('lite',!!SETTINGS.liteDefault);const accentMap={"macro-command":"cyan","terminal-green":"lime","crimson-desk":"red","minimal-dark":"ice","earth-at-night":"ice","grid-aura":"cyan","construction":"amber","aliens":"lime","nautical":"ice","neon-miami":"purple"};const baseAccent=ACCENTS[accentMap[SETTINGS.theme]||'cyan'];if(SETTINGS.innerEdgeTheme==='theme'){document.documentElement.style.setProperty('--inner-edge',`rgba(${baseAccent.rgb},.22)`)}else{const edge=ACCENTS[SETTINGS.innerEdgeTheme]||baseAccent;document.documentElement.style.setProperty('--inner-edge',`rgba(${edge.rgb},.22)`)}$('toggleLiteBtn').textContent=document.body.classList.contains('lite')?'Rich Mode':'Lite Mode'}
function populateGlobals(){$('finnhubToken').value=GLOBALS.finnhubToken||'';$('weeklyEvents').value=GLOBALS.weeklyEventsText||'';$('manualResultNotes').value=GLOBALS.manualResultNotes||''}
function readGlobals(){GLOBALS.finnhubToken=$('finnhubToken').value.trim();GLOBALS.weeklyEventsText=$('weeklyEvents').value;GLOBALS.manualResultNotes=$('manualResultNotes').value;saveGlobals()}
function openSettings(){$('settingRefreshSeconds').value=String(SETTINGS.refreshSeconds||60);$('settingNewsSeconds').value=String(SETTINGS.newsSeconds||300);$('settingChartInterval').value=SETTINGS.chartInterval||'15';$('settingLiteDefault').value=SETTINGS.liteDefault?'true':'false';$('settingTheme').value=SETTINGS.theme||'macro-command';$('settingTileStyle').value=SETTINGS.tileStyle||'glass';$('settingGlow').value=SETTINGS.glow||'low';$('settingDensity').value=SETTINGS.density||'comfortable';$('settingInnerEdgeTheme').value=SETTINGS.innerEdgeTheme||'theme';$('settingsBackdrop').style.display='flex'}
function closeSettings(){$('settingsBackdrop').style.display='none'}
function saveSettingsFromModal(){SETTINGS.refreshSeconds=parseInt($('settingRefreshSeconds').value||'60',10);SETTINGS.newsSeconds=parseInt($('settingNewsSeconds').value||'300',10);SETTINGS.chartInterval=$('settingChartInterval').value||'15';SETTINGS.liteDefault=$('settingLiteDefault').value==='true';SETTINGS.theme=$('settingTheme').value||'macro-command';SETTINGS.tileStyle=$('settingTileStyle').value||'glass';SETTINGS.glow=$('settingGlow').value||'low';SETTINGS.density=$('settingDensity').value||'comfortable';SETTINGS.innerEdgeTheme=$('settingInnerEdgeTheme').value||'theme';saveSettings();applyTheme();closeSettings();renderAll()}
function toggleLiteMode(){SETTINGS.liteDefault=!SETTINGS.liteDefault;saveSettings();applyTheme()}
function getTimePartsForZone(z){const n=new Date(),fmt=new Intl.DateTimeFormat('en-US',{timeZone:z,year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hour12:false}),parts=fmt.formatToParts(n),o={};for(const p of parts){if(p.type!=='literal')o[p.type]=parseInt(p.value,10)}return o}
function getTimeString(z){return new Intl.DateTimeFormat('en-US',{timeZone:z,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())}
function marketStatus(parts,openHour,closeHour){const n=parts.hour+(parts.minute/60);if(n>=openHour&&n<closeHour)return'OPEN';if(n>=openHour-1&&n<openHour)return'PRE';return'CLOSED'}
function formatCloseTime(c){const hr=Math.floor(c.close),min=Math.round((c.close-hr)*60);return `Closes ${String(hr).padStart(2,'0')}:${String(min).padStart(2,'0')} local`}
function renderClocks(){const g=$('clockStrip');g.innerHTML='';CLOCKS.forEach(c=>{const parts=getTimePartsForZone(c.tz),status=marketStatus(parts,c.open,c.close),cls=status==='OPEN'?'open':status==='PRE'?'pre':'closed';const card=document.createElement('div');card.className='glass-sm clock-card';card.innerHTML=`<div><div class="clock-city">${escapeHtml(c.city)}</div><div class="clock-label">${escapeHtml(c.label)}</div></div><div><div class="clock-time">${getTimeString(c.tz)}</div><div class="clock-close">${formatCloseTime(c)}</div></div><div class="clock-status ${cls}"><span class="dot"></span>${status}</div>`;g.appendChild(card)})}
function getNYParts(){return getTimePartsForZone('America/New_York')}
function getNYWallClockDate(){const p=getNYParts();return new Date(Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second))}
function buildWallClockDate(y,m,d,h,mi){return new Date(Date.UTC(y,m-1,d,h,mi,0))}
function getSessionState(parts){const total=parts.hour*60+parts.minute,isLondon=total>=180&&total<480,isNY=total>=480&&total<1020,isAsia=total>=1140||total<180;let label='Reset / Between Sessions';if(isLondon)label='London Session';else if(isNY)label='New York Session';else if(isAsia)label='Asia Session';return{isLondon,isNY,isAsia,label}}
function parseWeeklyEvents(text){const lines=String(text||'').split('\n').map(x=>x.trim()).filter(Boolean),events=[];for(const line of lines){const parts=line.split('|');if(parts.length<2)continue;const [datePart,timePart]=parts[0].trim().split(' ');if(!datePart||!timePart)continue;const [yy,mm,dd]=datePart.split('-').map(Number),[hh,mi]=timePart.split(':').map(Number);if(![yy,mm,dd,hh,mi].every(Number.isFinite))continue;events.push({name:parts[1].trim(),currency:parts[2]?parts[2].trim().toUpperCase():'',date:buildWallClockDate(yy,mm,dd,hh,mi),dateText:`${yy}-${String(mm).padStart(2,'0')}-${String(dd).padStart(2,'0')}`,timeText:`${String(hh).padStart(2,'0')}:${String(mi).padStart(2,'0')} ET`})}return events.sort((a,b)=>a.date-b.date)}
function getRedFolderStatus(){const now=getNYWallClockDate(),events=parseWeeklyEvents(GLOBALS.weeklyEventsText),next24h=events.filter(e=>{const d=(e.date-now)/60000;return d>=0&&d<=1440}),week=events.filter(e=>{const d=(e.date-now)/60000;return d>=-10&&d<=10080}),p=getNYParts(),todayText=`${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`,today=events.filter(e=>e.dateText===todayText),releasedToday=today.filter(e=>e.date<=now);return{next24h,week,today,releasedToday}}
function detectAssetClass(symbol){if(CRYPTO_CG_MAP[symbol])return'crypto';if(FUTURES_PROXY_MAP[symbol])return'futures';return'forex'}
function getChartSymbol(symbol,cls){if(cls==='crypto')return`BINANCE:${symbol.replace('USD','')}USDT`;if(cls==='forex')return`OANDA:${symbol}`;return symbol}
function normalizeAsset(asset){const raw=(asset.symbol||'').toUpperCase().trim(),fut=FUTURES_PROXY_MAP[raw];if(fut)return{...asset,symbol:raw,normalizedSymbol:fut.proxySymbol,effectiveClass:'forex',chartSymbol:fut.chartSymbol,quoteSymbol:fut.quoteSymbol,proxyNote:fut.note};const cls=asset.assetClass==='auto'?detectAssetClass(raw):asset.assetClass;return{...asset,symbol:raw,normalizedSymbol:raw,effectiveClass:cls,chartSymbol:getChartSymbol(raw,cls),quoteSymbol:raw,proxyNote:''}}
async function fetchCryptoPrices(ids){if(!ids.length)return{};const data=await safeJsonFetch(`https://api.coingecko.com/api/v3/simple/price?ids=${encodeURIComponent([...new Set(ids)].join(','))}&vs_currencies=usd`,4500);if(!data)return{};const out={};Object.keys(data).forEach(id=>out[id]=data[id]?.usd);return out}
async function fetchFinnhubQuote(symbol){if(!GLOBALS.finnhubToken)return null;const data=await safeJsonFetch(`https://finnhub.io/api/v1/quote?symbol=${encodeURIComponent(symbol)}&token=${encodeURIComponent(GLOBALS.finnhubToken)}`,4500);return data&&typeof data.c==='number'&&data.c>0?data.c:null}
async function fetchYahooPDHPDL(symbol){const data=await safeJsonFetch('https://api.allorigins.win/raw?url='+encodeURIComponent(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5d&interval=1d`),5000),result=data?.chart?.result?.[0],quote=result?.indicators?.quote?.[0],highs=quote?.high||[],lows=quote?.low||[],usable=[];for(let i=0;i<highs.length;i++){if(typeof highs[i]==='number'&&typeof lows[i]==='number')usable.push({high:highs[i],low:lows[i]})}if(!usable.length)return null;const pick=usable.length>=2?usable[usable.length-2]:usable[usable.length-1];return{high:pick.high,low:pick.low}}
async function refreshPrices(){let liveCount=0,fallbackCount=0;const normalized=ASSETS.map(normalizeAsset),cryptoAssets=normalized.filter(a=>(a.priceSource==='auto'||a.priceSource==='coingecko')&&a.effectiveClass==='crypto'),cryptoIds=cryptoAssets.map(a=>CRYPTO_CG_MAP[a.normalizedSymbol]).filter(Boolean),cgPrices=await fetchCryptoPrices(cryptoIds);ASSETS=ASSETS.map(asset=>{const n=normalizeAsset(asset);if((asset.priceSource==='auto'||asset.priceSource==='coingecko')&&n.effectiveClass==='crypto'){const cgId=CRYPTO_CG_MAP[n.normalizedSymbol],px=cgId?cgPrices[cgId]:null;if(typeof px==='number'&&px>0){liveCount++;return{...asset,previousPrice:asset.currentPrice,currentPrice:px,lastSource:'CoinGecko',priceStatus:'Live',updatedAt:Date.now()}}fallbackCount++;return{...asset,lastSource:'Manual',priceStatus:'Fallback'}}return asset});for(let i=0;i<ASSETS.length;i++){const asset=ASSETS[i],n=normalizeAsset(asset);if((asset.priceSource==='auto'||asset.priceSource==='finnhub')&&n.effectiveClass!=='crypto'&&GLOBALS.finnhubToken){const px=await fetchFinnhubQuote(n.quoteSymbol);if(typeof px==='number'&&px>0){liveCount++;ASSETS[i]={...ASSETS[i],previousPrice:ASSETS[i].currentPrice,currentPrice:px,lastSource:'Finnhub',priceStatus:'Live',updatedAt:Date.now()}}else{fallbackCount++;ASSETS[i]={...ASSETS[i],lastSource:'Manual',priceStatus:'Fallback'}}}}
priceHealth=liveCount>0?(fallbackCount>0?'Partial Live':'Live'):'Manual / Fallback';lastPriceRefresh=Date.now();saveAssets()}
function evaluateAsset(asset){const a=normalizeAsset(asset),session=getSessionState(getNYParts()),price=Number(a.currentPrice),prev=Number(a.previousPrice),pdh=Number(a.pdh),pdl=Number(a.pdl),buffer=Number(a.retestBuffer),failedHigh=prev>pdh&&price<pdh,failedLow=prev<pdl&&price>pdl,nearPDH=price>=pdh-buffer&&price<=pdh+buffer,nearPDL=price>=pdl-buffer&&price<=pdl+buffer;let setupModel='None',bias='Range',verdict='WAIT',verdictColor='mid',entryZone='-',invalidation='-',target1='-';if(price>pdh){setupModel='Expansion';bias='Bullish Confirmed';verdict=nearPDH?'TRADE':'WAIT';verdictColor=nearPDH?'high':'mid';entryZone=`${formatPrice(pdh-buffer)} - ${formatPrice(pdh+buffer)}`;invalidation=formatPrice(pdh-buffer-0.02);target1=formatPrice(pdh+0.20)}else if(price<pdl){setupModel='Expansion';bias='Bearish Confirmed';verdict=nearPDL?'TRADE':'WAIT';verdictColor=nearPDL?'high':'mid';entryZone=`${formatPrice(pdl-buffer)} - ${formatPrice(pdl+buffer)}`;invalidation=formatPrice(pdl+buffer+0.02);target1=formatPrice(pdl-0.20)}else if(failedHigh){setupModel='High/Low Failure';bias='High Failure';verdict='TRADE';verdictColor='high';entryZone=`${formatPrice(pdh-buffer)} - ${formatPrice(pdh)}`;invalidation=formatPrice(pdh+buffer);target1=formatPrice((pdh+pdl)/2)}else if(failedLow){setupModel='High/Low Failure';bias='Low Failure';verdict='TRADE';verdictColor='high';entryZone=`${formatPrice(pdl)} - ${formatPrice(pdl+buffer)}`;invalidation=formatPrice(pdl-buffer);target1=formatPrice((pdh+pdl)/2)}else{verdict='NO TRADE';verdictColor='low'}if(!(session.isLondon||session.isNY)){verdict='NO TRADE';verdictColor='low'}return{...a,price,setupModel,bias,verdict,verdictColor,entryZone,invalidation,target1,sessionLabel:session.label}}
function scoreHeadline(title,watchSymbols){const t=String(title||'').toLowerCase();let score=0;['cpi','inflation','fed','fomc','rates','yield','jobs','nfp','pce','ppi','bitcoin','crypto','gold','oil','treasury','recession','tariff','stocks','dollar'].forEach(k=>{if(t.includes(k))score+=3});watchSymbols.forEach(sym=>{const base=sym.toLowerCase().replace('usd','');if(base&&t.includes(base))score+=1});if(['surge','crash','spike','plunge','rally','selloff'].some(k=>t.includes(k)))score+=2;return score}
function newsIntelScoreStory(s){let base=50;const mins=Math.round((Date.now()-s.time)/60000);if(mins<10)base+=18;else if(mins<60)base+=10;else if(mins>240)base-=10;if((s.summary||'').length>20)base+=10;if(s.red)base+=20;base+=Math.min(12,s.relevanceScore||0);return Math.max(0,Math.min(100,Math.round(base)))}
function newsIntelFinalScore(s){const src=NEWS_INTEL_SOURCES[s.source]?.score||50,story=newsIntelScoreStory(s);return Math.round(src*.45+story*.55)}
function limitStoriesBySource(stories,maxTotal=10,maxPerSource=2){const counts={},out=[];for(const s of stories){const key=s.source||'unknown';counts[key]=counts[key]||0;if(counts[key]>=maxPerSource)continue;out.push(s);counts[key]++;if(out.length>=maxTotal)break}return out}
function computeBias(){const evals=ASSETS.map(a=>evaluateAsset(a)),longs=evals.filter(e=>e.bias.includes('Bullish')||e.bias.includes('Low Failure')).length,shorts=evals.filter(e=>e.bias.includes('Bearish')||e.bias.includes('High Failure')).length;if(longs>shorts)return'Risk-On';if(shorts>longs)return'Risk-Off';return'Mixed'}
function strongestSetup(){const rank={TRADE:0,WAIT:1,'NO TRADE':2};return ASSETS.map(a=>evaluateAsset(a)).sort((a,b)=>rank[a.verdict]-rank[b.verdict])[0]||null}
function getAssetMovePct(symbol){const a=ASSETS.find(x=>(x.symbol||'').toUpperCase()===symbol);if(!a)return null;const c=Number(a.currentPrice),p=Number(a.previousPrice);if(!Number.isFinite(c)||!Number.isFinite(p)||p===0)return null;return((c-p)/Math.abs(p))*100}
function inferResolutionBias(currency){if(currency==='USD'){const uj=getAssetMovePct('USDJPY'),eu=getAssetMovePct('EURUSD');if(uj!==null&&eu!==null){if(uj>0&&eu<0)return'Likely USD bullish reaction';if(uj<0&&eu>0)return'Likely USD bearish reaction'}}return'Mixed likely outcome'}
function forecastNextEventOutcome(){const red=getRedFolderStatus(),next=red.next24h[0];if(!next)return {headline:'No imminent red-folder event.',detail:'Forecast module standing by.'};const rankedSources=Object.values(NEWS_INTEL_SOURCES).sort((a,b)=>(b.score+b.forecast)-(a.score+a.forecast)).slice(0,3).map(s=>s.name).join(', ');return {headline:inferResolutionBias(next.currency),detail:`Based on the highest-consistency forecasting sources: ${rankedSources}.`}}
function renderCommandStrip(){const session=getSessionState(getNYParts()),red=getRedFolderStatus(),next=red.next24h[0],best=strongestSetup();$('currentSessionCard').textContent=session.label;$('nextEventCard').textContent=next?`${next.name} • ${formatCountdown(next.date.getTime())}`:'Clear';$('nextEventTile').classList.toggle('alert-red',!!next);$('biasCard').textContent=computeBias();$('bestSetupCard').textContent=best?`${best.symbol} • ${best.verdict}`:'None';$('statusCard').textContent=`${priceHealth}`}
function renderWatchlistSummaryHtml(){const rank={TRADE:0,WAIT:1,'NO TRADE':2},results=ASSETS.map(a=>evaluateAsset(a)).sort((a,b)=>rank[a.verdict]-rank[b.verdict]);if(!results.length)return '<div class="subtle">No assets in watchlist.</div>';return results.map(r=>`<div class="glass-sm row"><div><div class="row-title">${escapeHtml(r.symbol)}</div><div class="row-meta">${escapeHtml(r.bias)} • ${escapeHtml(r.setupModel)}</div></div><div style="text-align:right;"><div class="row-title">${formatPrice(r.price)}</div><div class="row-meta ${r.verdictColor}">${escapeHtml(r.verdict)}</div></div></div>`).join('')}
function removeAsset(id){ASSETS=ASSETS.filter(a=>a.id!==id);saveAssets();renderAll();renderNewsIntel()}
window.removeAsset=removeAsset;
function renderAssets(){const grid=$('assetGrid'),rank={TRADE:0,WAIT:1,'NO TRADE':2},sorted=[...ASSETS].sort((a,b)=>rank[evaluateAsset(a).verdict]-rank[evaluateAsset(b).verdict]);grid.innerHTML='';sorted.forEach(asset=>{const r=evaluateAsset(asset),card=document.createElement('div');card.className='glass-sm asset-card';card.innerHTML=`<div class="asset-head"><div class="asset-main"><div class="asset-symbol"><strong>${escapeHtml(r.symbol)}</strong><span class="pill ${r.verdict==='TRADE'?'pill-trade':r.verdict==='WAIT'?'pill-wait':'pill-no'}">${escapeHtml(r.verdict)}</span></div><div class="asset-meta">${escapeHtml(r.bias)} • ${escapeHtml(r.setupModel)} • ${escapeHtml(r.sessionLabel)}</div></div><div class="asset-side"><div class="row-title">${formatPrice(r.price)}</div><div class="row-meta text-ellipsis">${escapeHtml(asset.lastSource||'Manual')}</div></div></div><div class="metric-grid"><div class="glass-sm metric"><div class="metric-label">Entry Zone</div><div class="metric-value">${escapeHtml(r.entryZone)}</div></div><div class="glass-sm metric"><div class="metric-label">Invalidation</div><div class="metric-value">${escapeHtml(r.invalidation)}</div></div><div class="glass-sm metric"><div class="metric-label">Target 1</div><div class="metric-value">${escapeHtml(r.target1)}</div></div><div class="glass-sm metric"><div class="metric-label">Current</div><div class="metric-value">${formatPrice(asset.currentPrice)}</div></div></div><div class="provider-badge-row"><span class="provider-badge ${asset.priceStatus==='Live'?'live':asset.priceStatus==='Fallback'?'fallback':'cached'}">${escapeHtml(asset.priceStatus||'Manual')}</span><span class="provider-badge">${escapeHtml(asset.lastSource||'Manual')}</span></div><div class="asset-actions"><button class="btn small red" onclick="removeAsset('${asset.id}')">Remove</button></div>`;grid.appendChild(card)})}
function renderRedFolderModule(){const {next24h,week,today,releasedToday}=getRedFolderStatus();document.querySelectorAll('.tab-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===SETTINGS.redFolderTab));document.querySelectorAll('.tab-pane').forEach(p=>p.classList.toggle('active',p.dataset.tab===SETTINGS.redFolderTab));const nextBox=$('redTabNext'),todayBox=$('redTabToday'),weekBox=$('redTabWeek'),reactBox=$('redTabReaction');nextBox.innerHTML='';todayBox.innerHTML='';weekBox.innerHTML='';reactBox.innerHTML='';if(next24h.length){const e=next24h[0];nextBox.innerHTML=`<div class="glass-sm section"><div class="row-title">${escapeHtml(e.name)}</div><div class="subtle" style="margin-top:6px;">${escapeHtml(e.dateText)} • ${escapeHtml(e.timeText)}${e.currency?' • '+escapeHtml(e.currency):''}</div><div style="margin-top:10px;">Release in ${formatCountdown(e.date.getTime())}</div></div>`}else nextBox.innerHTML='<div class="subtle">No next event inside 24 hours.</div>';todayBox.innerHTML=today.length?'':'<div class="subtle">No events today.</div>';today.forEach(e=>{const row=document.createElement('div');row.className='glass-sm row';row.innerHTML=`<div><div class="row-title">${escapeHtml(e.name)}</div><div class="row-meta">${escapeHtml(e.currency||'Macro')}</div></div><div class="row-title">${escapeHtml(e.timeText)}</div>`;todayBox.appendChild(row)});weekBox.innerHTML=week.length?'':'<div class="subtle">No weekly events listed.</div>';week.forEach(e=>{const row=document.createElement('div');row.className='glass-sm row';row.innerHTML=`<div><div class="row-title">${escapeHtml(e.name)}</div><div class="row-meta">${escapeHtml(e.dateText)}${e.currency?' • '+escapeHtml(e.currency):''}</div></div><div class="row-title">${escapeHtml(e.timeText)}</div>`;weekBox.appendChild(row)});if(releasedToday.length){const latest=releasedToday[releasedToday.length-1];reactBox.innerHTML=`<div class="glass-sm section"><div class="row-title">${escapeHtml(latest.name)}</div><div style="margin-top:8px;"><span class="subtle">Reaction:</span> ${escapeHtml(inferResolutionBias(latest.currency))}</div><div style="margin-top:8px;"><span class="subtle">Manual notes:</span> ${escapeHtml(GLOBALS.manualResultNotes||'None entered.')}</div></div>`}else reactBox.innerHTML=`<div class="subtle">No released event to evaluate.</div>`}
function activateRedTab(tab){SETTINGS.redFolderTab=tab;saveSettings();renderRedFolderModule()}
function renderProviderPrep(){const root=$('providerPrepRoot');if(!root)return;root.innerHTML=`<div class="provider-prep-grid"><div class="glass-sm section"><div class="section-title">Primary Feed Prep</div><div class="row-title">Ready for Twelve Data</div><div class="notice-line">Hook point prepared for broad free coverage across forex, crypto, and US ETFs/stocks.</div></div><div class="glass-sm section"><div class="section-title">Crypto Fallback Prep</div><div class="row-title">CoinGecko in place</div><div class="notice-line">Current crypto path can remain the fallback validator when a main provider is added.</div></div><div class="glass-sm section"><div class="section-title">Status Model</div><div class="row-title">Live / Cached / Fallback</div><div class="notice-line">Badges and provider labels are already prepared in the asset cards.</div></div></div>`}
function renderNewsIntel(){const root=$('newsIntelRoot');const ranked=NEWS_INTEL_STORIES.map(s=>({...s,storyScore:newsIntelScoreStory(s),final:newsIntelFinalScore(s)})).sort((a,b)=>b.final-a.final);const limited=limitStoriesBySource(ranked,10,2);const forecast=forecastNextEventOutcome();const storiesHtml=limited.map((s,idx)=>{const cls=s.final>=80?'high':s.final>=60?'mid':'low';const sourceName=NEWS_INTEL_SOURCES[s.source]?.name||s.source;return `<div class="story ${idx===0?'top':''}"><div class="story-rank">#${idx+1} • ${escapeHtml(sourceName)} • ${formatAgo(s.time)}</div><div class="story-title">${s.link?`<a href="${s.link}" target="_blank">${escapeHtml(s.title)}</a>`:escapeHtml(s.title)}</div><div class="story-summary">${escapeHtml((s.summary||'').slice(0,260))}</div><div class="story-score ${cls}">Overall: ${s.final} | Source: ${NEWS_INTEL_SOURCES[s.source]?.score||50} | Story: ${s.storyScore}</div></div>`}).join('');const leaderboard=Object.entries(NEWS_INTEL_SOURCES).sort((a,b)=>b[1].score-a[1].score).map(([key,s])=>{const count=limited.filter(x=>x.source===key).length;return `<tr><td>${escapeHtml(s.name)}</td><td>${s.score}</td><td>${count}</td></tr>`}).join('');root.innerHTML=`<div class="news-layout"><div class="story-stack">${storiesHtml||'<div class="subtle">No ranked stories yet.</div>'}</div><div class="side-stack"><div class="glass-sm section"><div class="section-title">Source Scores</div><table class="table"><thead><tr><th>Source</th><th>Score</th><th>Top 10</th></tr></thead><tbody>${leaderboard}</tbody></table></div><div class="glass-sm section"><div class="section-title">Feed Rules</div><div class="subtle">Top 10 overall stories.<br>Maximum two stories per source.<br>Weighted by source reliability and story importance.</div></div><div class="glass-sm section"><div class="section-title">Watchlist Command Summary</div><div class="list">${renderWatchlistSummaryHtml()}</div></div><div class="glass-sm section"><div class="section-title">Next Red Folder Likely Outcome</div><div class="row-title">${escapeHtml(forecast.headline)}</div><div class="subtle" style="margin-top:8px;">${escapeHtml(forecast.detail)}</div></div></div></div>`}
async function loadRssItems(feedUrl,sourceKey,watchSymbols,limit=6){const data=await safeJsonFetch('https://api.rss2json.com/v1/api.json?rss_url='+encodeURIComponent(feedUrl),6000);if(!data?.items?.length)return[];return data.items.slice(0,limit).map(item=>({source:sourceKey,title:item.title||'Untitled',summary:(item.description||item.content||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()||'Market story.',time:item.pubDate?Date.parse(item.pubDate):Date.now(),red:/cpi|inflation|fed|fomc|nfp|jobs|rates|pce|ppi/i.test(item.title||''),link:item.link,relevanceScore:scoreHeadline(item.title,watchSymbols)})).sort((a,b)=>b.relevanceScore-a.relevanceScore)}
async function loadCoinBureauItems(watchSymbols,limit=6){const html=await safeTextFetch('https://api.allorigins.win/raw?url='+encodeURIComponent('https://coinbureau.com/'),6000);if(!html)return[];try{const doc=new DOMParser().parseFromString(html,'text/html'),anchors=Array.from(doc.querySelectorAll('a[href]')),candidates=anchors.map(a=>({href:a.getAttribute('href')||'',text:(a.textContent||'').replace(/\s+/g,' ').trim()})).filter(x=>x.href.includes('coinbureau.com/')&&x.text.length>20);const uniq=[];const seen=new Set();for(const c of candidates){if(seen.has(c.href))continue;seen.add(c.href);uniq.push(c);if(uniq.length>=limit)break}return uniq.map(c=>({source:'coinbureau',title:c.text,summary:'Crypto-focused market analysis and commentary.',time:Date.now()-180000,red:/bitcoin|crypto|etf|fed|rates/i.test(c.text||''),link:c.href,relevanceScore:scoreHeadline(c.text,watchSymbols)})).sort((a,b)=>b.relevanceScore-a.relevanceScore)}catch{return[]}}
async function renderNews(){const watchSymbols=ASSETS.map(a=>(a.symbol||'').toUpperCase());const results=await Promise.allSettled([loadRssItems('https://feeds.feedburner.com/zerohedge/feed','zerohedge',watchSymbols,6),loadRssItems('https://www.fxstreet.com/rss/news','fxstreet',watchSymbols,6),loadRssItems('https://cointelegraph.com/rss','cointelegraph',watchSymbols,6),loadCoinBureauItems(watchSymbols,6)]);const items=results.flatMap(r=>r.status==='fulfilled'?(r.value||[]):[]);if(!items.length){newsHealth='Fallback';NEWS_INTEL_STORIES=[{source:'fxstreet',title:'Open FXStreet',summary:'Direct site fallback.',time:Date.now()-60000,red:false,link:'https://www.fxstreet.com/news',relevanceScore:5}]}else{newsHealth='Live';NEWS_INTEL_STORIES=items.sort((a,b)=>newsIntelFinalScore(b)-newsIntelFinalScore(a))}renderNewsIntel()}
async function addAsset(){const symbol=$('newSymbol').value.trim().toUpperCase();if(!symbol)return;const exists=ASSETS.find(a=>(a.symbol||'').toUpperCase()===symbol);if(exists){alert(`${symbol} is already on the dashboard. Remove it first or update the existing entry.`);return;}const assetClass=$('newAssetClass').value,priceSource=$('newPriceSource').value;let pdh=safeParseNum($('newPDH').value),pdl=safeParseNum($('newPDL').value);if(!pdh||!pdl){const autoPD=await fetchYahooPDHPDL(symbol);if(!pdh)pdh=autoPD?.high;if(!pdl)pdl=autoPD?.low}ASSETS.push({id:mkid(),symbol,assetClass,priceSource,currentPrice:safeParseNum($('newCurrentPrice').value),previousPrice:safeParseNum($('newPreviousPrice').value),pdh,pdl,retestBuffer:safeParseNum($('newRetestBuffer').value)??0.03,autoPrice:priceSource!=='manual',lastSource:priceSource==='manual'?'Manual':'Pending',priceStatus:priceSource==='manual'?'Manual':'Pending',updatedAt:null});saveAssets();await refreshPrices();renderAll();renderNewsIntel()}
async function manualRefresh(){readGlobals();$('statusCard').textContent='Refreshing…';await Promise.allSettled([refreshPrices(),renderNews()]);renderAll()}
function renderAll(){renderClocks();renderCommandStrip();renderRedFolderModule();renderAssets();renderProviderPrep();$('priceHealthMini').textContent=priceHealth;$('newsHealthMini').textContent=newsHealth;$('lastRefreshMini').textContent=lastPriceRefresh?new Date(lastPriceRefresh).toLocaleTimeString():'-'}
$('refreshBtn').onclick=manualRefresh;$('saveGlobalsBtn').onclick=()=>{readGlobals();renderRedFolderModule()};$('toggleLiteBtn').onclick=toggleLiteMode;$('openSettingsBtn').onclick=openSettings;$('closeSettingsBtn').onclick=closeSettings;$('saveSettingsBtn').onclick=saveSettingsFromModal;$('settingsBackdrop').onclick=e=>{if(e.target.id==='settingsBackdrop')closeSettings()};$('addAssetBtn').onclick=addAsset;document.querySelectorAll('.tab-btn').forEach(btn=>btn.onclick=()=>activateRedTab(btn.dataset.tab));
(async function init(){applyTheme();populateGlobals();renderClocks();await Promise.allSettled([refreshPrices(),renderNews()]);renderAll();setInterval(renderClocks,1000);setInterval(renderCommandStrip,15000);setInterval(renderRedFolderModule,1000);setInterval(async()=>{await refreshPrices();renderAll()},(SETTINGS.refreshSeconds||60)*1000);setInterval(async()=>{await renderNews();renderCommandStrip()},(SETTINGS.newsSeconds||300)*1000)})();
